# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passwordmanager.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Login_page(object):
    def setupUi(self, Login_page):
        Login_page.setObjectName("Login_page")
        Login_page.resize(937, 673)
        self.centralwidget = QtWidgets.QWidget(Login_page)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 110, 651, 521))
        self.gridLayoutWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 2, 2)
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.label51 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label51.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label51.setObjectName("label51")
        self.gridLayout.addWidget(self.label51, 4, 0, 1, 1)
        self.label88 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label88.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label88.setObjectName("label88")
        self.gridLayout.addWidget(self.label88, 7, 7, 1, 1)
        self.label87 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label87.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label87.setObjectName("label87")
        self.gridLayout.addWidget(self.label87, 7, 6, 1, 1)
        self.label52 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label52.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label52.setObjectName("label52")
        self.gridLayout.addWidget(self.label52, 4, 1, 1, 1)
        self.label48 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label48.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label48.setObjectName("label48")
        self.gridLayout.addWidget(self.label48, 3, 7, 1, 1)
        self.label78 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label78.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label78.setObjectName("label78")
        self.gridLayout.addWidget(self.label78, 6, 7, 1, 1)
        self.label77 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label77.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label77.setObjectName("label77")
        self.gridLayout.addWidget(self.label77, 6, 6, 1, 1)
        self.label81 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label81.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label81.setObjectName("label81")
        self.gridLayout.addWidget(self.label81, 7, 0, 1, 1)
        self.label34 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label34.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label34.setObjectName("label34")
        self.gridLayout.addWidget(self.label34, 2, 3, 1, 1)
        self.label35 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label35.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label35.setObjectName("label35")
        self.gridLayout.addWidget(self.label35, 2, 4, 1, 1)
        self.label36 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label36.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label36.setObjectName("label36")
        self.gridLayout.addWidget(self.label36, 2, 5, 1, 1)
        self.label22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label22.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label22.setObjectName("label22")
        self.gridLayout.addWidget(self.label22, 1, 1, 1, 1)
        self.label31 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label31.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label31.setObjectName("label31")
        self.gridLayout.addWidget(self.label31, 2, 0, 1, 1)
        self.label33 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label33.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label33.setObjectName("label33")
        self.gridLayout.addWidget(self.label33, 2, 2, 1, 1)
        self.label28 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label28.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label28.setObjectName("label28")
        self.gridLayout.addWidget(self.label28, 1, 7, 1, 1)
        self.label32 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label32.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label32.setObjectName("label32")
        self.gridLayout.addWidget(self.label32, 2, 1, 1, 1)
        self.label23 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label23.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label23.setObjectName("label23")
        self.gridLayout.addWidget(self.label23, 1, 2, 1, 1)
        self.label26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label26.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label26.setObjectName("label26")
        self.gridLayout.addWidget(self.label26, 1, 5, 1, 1)
        self.label24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label24.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label24.setObjectName("label24")
        self.gridLayout.addWidget(self.label24, 1, 3, 1, 1)
        self.label25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label25.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label25.setObjectName("label25")
        self.gridLayout.addWidget(self.label25, 1, 4, 1, 1)
        self.label44 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label44.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label44.setObjectName("label44")
        self.gridLayout.addWidget(self.label44, 3, 3, 1, 1)
        self.label16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label16.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label16.setObjectName("label16")
        self.gridLayout.addWidget(self.label16, 0, 5, 1, 1)
        self.label38 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label38.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label38.setObjectName("label38")
        self.gridLayout.addWidget(self.label38, 2, 7, 1, 1)
        self.label37 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label37.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label37.setObjectName("label37")
        self.gridLayout.addWidget(self.label37, 2, 6, 1, 1)
        self.label43 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label43.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label43.setObjectName("label43")
        self.gridLayout.addWidget(self.label43, 3, 2, 1, 1)
        self.label42 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label42.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label42.setObjectName("label42")
        self.gridLayout.addWidget(self.label42, 3, 1, 1, 1)
        self.label45 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label45.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label45.setObjectName("label45")
        self.gridLayout.addWidget(self.label45, 3, 4, 1, 1)
        self.label46 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label46.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label46.setObjectName("label46")
        self.gridLayout.addWidget(self.label46, 3, 5, 1, 1)
        self.label47 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label47.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label47.setObjectName("label47")
        self.gridLayout.addWidget(self.label47, 3, 6, 1, 1)
        self.label27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label27.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label27.setObjectName("label27")
        self.gridLayout.addWidget(self.label27, 1, 6, 1, 1)
        self.label82 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label82.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label82.setObjectName("label82")
        self.gridLayout.addWidget(self.label82, 7, 1, 1, 1)
        self.label83 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label83.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label83.setObjectName("label83")
        self.gridLayout.addWidget(self.label83, 7, 2, 1, 1)
        self.label84 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label84.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label84.setObjectName("label84")
        self.gridLayout.addWidget(self.label84, 7, 3, 1, 1)
        self.label85 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label85.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label85.setObjectName("label85")
        self.gridLayout.addWidget(self.label85, 7, 4, 1, 1)
        self.label86 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label86.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label86.setObjectName("label86")
        self.gridLayout.addWidget(self.label86, 7, 5, 1, 1)
        self.label54 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label54.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label54.setObjectName("label54")
        self.gridLayout.addWidget(self.label54, 4, 3, 1, 1)
        self.label72 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label72.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label72.setObjectName("label72")
        self.gridLayout.addWidget(self.label72, 6, 1, 1, 1)
        self.label57 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label57.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label57.setObjectName("label57")
        self.gridLayout.addWidget(self.label57, 4, 6, 1, 1)
        self.label64 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label64.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label64.setObjectName("label64")
        self.gridLayout.addWidget(self.label64, 5, 3, 1, 1)
        self.label53 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label53.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label53.setObjectName("label53")
        self.gridLayout.addWidget(self.label53, 4, 2, 1, 1)
        self.label56 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label56.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label56.setObjectName("label56")
        self.gridLayout.addWidget(self.label56, 4, 5, 1, 1)
        self.label58 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label58.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label58.setObjectName("label58")
        self.gridLayout.addWidget(self.label58, 4, 7, 1, 1)
        self.label73 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label73.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label73.setObjectName("label73")
        self.gridLayout.addWidget(self.label73, 6, 2, 1, 1)
        self.label61 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label61.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label61.setObjectName("label61")
        self.gridLayout.addWidget(self.label61, 5, 0, 1, 1)
        self.label63 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label63.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label63.setObjectName("label63")
        self.gridLayout.addWidget(self.label63, 5, 2, 1, 1)
        self.label62 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label62.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label62.setObjectName("label62")
        self.gridLayout.addWidget(self.label62, 5, 1, 1, 1)
        self.label14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label14.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label14.setObjectName("label14")
        self.gridLayout.addWidget(self.label14, 0, 3, 1, 1)
        self.label11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label11.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label11.setObjectName("label11")
        self.gridLayout.addWidget(self.label11, 0, 0, 1, 1)
        self.label13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label13.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label13.setObjectName("label13")
        self.gridLayout.addWidget(self.label13, 0, 2, 1, 1)
        self.label15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label15.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label15.setObjectName("label15")
        self.gridLayout.addWidget(self.label15, 0, 4, 1, 1)
        self.label66 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label66.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label66.setObjectName("label66")
        self.gridLayout.addWidget(self.label66, 5, 5, 1, 1)
        self.label65 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label65.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label65.setObjectName("label65")
        self.gridLayout.addWidget(self.label65, 5, 4, 1, 1)
        self.label17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label17.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label17.setObjectName("label17")
        self.gridLayout.addWidget(self.label17, 0, 6, 1, 1)
        self.label74 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label74.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label74.setObjectName("label74")
        self.gridLayout.addWidget(self.label74, 6, 3, 1, 1)
        self.label18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label18.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label18.setObjectName("label18")
        self.gridLayout.addWidget(self.label18, 0, 7, 1, 1)
        self.label76 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label76.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label76.setObjectName("label76")
        self.gridLayout.addWidget(self.label76, 6, 5, 1, 1)
        self.label21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label21.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label21.setObjectName("label21")
        self.gridLayout.addWidget(self.label21, 1, 0, 1, 1)
        self.label12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label12.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label12.setObjectName("label12")
        self.gridLayout.addWidget(self.label12, 0, 1, 1, 1)
        self.label67 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label67.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label67.setObjectName("label67")
        self.gridLayout.addWidget(self.label67, 5, 6, 1, 1)
        self.label41 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label41.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label41.setObjectName("label41")
        self.gridLayout.addWidget(self.label41, 3, 0, 1, 1)
        self.label68 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label68.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label68.setObjectName("label68")
        self.gridLayout.addWidget(self.label68, 5, 7, 1, 1)
        self.label71 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label71.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label71.setObjectName("label71")
        self.gridLayout.addWidget(self.label71, 6, 0, 1, 1)
        self.label75 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label75.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label75.setObjectName("label75")
        self.gridLayout.addWidget(self.label75, 6, 4, 1, 1)
        self.label55 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label55.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label55.setObjectName("label55")
        self.gridLayout.addWidget(self.label55, 4, 4, 1, 1)
        self.New_btn = QtWidgets.QPushButton(self.centralwidget)
        self.New_btn.setEnabled(True)
        self.New_btn.setGeometry(QtCore.QRect(50, 50, 191, 28))
        self.New_btn.setObjectName("New_btn")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(280, 50, 231, 31))
        self.comboBox.setAcceptDrops(False)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(750, 230, 131, 81))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(750, 350, 131, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        Login_page.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(Login_page)
        self.statusBar.setObjectName("statusBar")
        Login_page.setStatusBar(self.statusBar)

        self.retranslateUi(Login_page)
        QtCore.QMetaObject.connectSlotsByName(Login_page)

    def retranslateUi(self, Login_page):
        _translate = QtCore.QCoreApplication.translate
        Login_page.setWindowTitle(_translate("Login_page", "PasswordManager--Login"))
        self.label51.setText(_translate("Login_page", "TextLabel"))
        self.label88.setText(_translate("Login_page", "TextLabel"))
        self.label87.setText(_translate("Login_page", "TextLabel"))
        self.label52.setText(_translate("Login_page", "TextLabel"))
        self.label48.setText(_translate("Login_page", "TextLabel"))
        self.label78.setText(_translate("Login_page", "TextLabel"))
        self.label77.setText(_translate("Login_page", "TextLabel"))
        self.label81.setText(_translate("Login_page", "TextLabel"))
        self.label34.setText(_translate("Login_page", "TextLabel"))
        self.label35.setText(_translate("Login_page", "TextLabel"))
        self.label36.setText(_translate("Login_page", "TextLabel"))
        self.label22.setText(_translate("Login_page", "TextLabel"))
        self.label31.setText(_translate("Login_page", "TextLabel"))
        self.label33.setText(_translate("Login_page", "TextLabel"))
        self.label28.setText(_translate("Login_page", "TextLabel"))
        self.label32.setText(_translate("Login_page", "TextLabel"))
        self.label23.setText(_translate("Login_page", "TextLabel"))
        self.label26.setText(_translate("Login_page", "TextLabel"))
        self.label24.setText(_translate("Login_page", "TextLabel"))
        self.label25.setText(_translate("Login_page", "TextLabel"))
        self.label44.setText(_translate("Login_page", "TextLabel"))
        self.label16.setText(_translate("Login_page", "TextLabel"))
        self.label38.setText(_translate("Login_page", "TextLabel"))
        self.label37.setText(_translate("Login_page", "TextLabel"))
        self.label43.setText(_translate("Login_page", "TextLabel"))
        self.label42.setText(_translate("Login_page", "TextLabel"))
        self.label45.setText(_translate("Login_page", "TextLabel"))
        self.label46.setText(_translate("Login_page", "TextLabel"))
        self.label47.setText(_translate("Login_page", "TextLabel"))
        self.label27.setText(_translate("Login_page", "TextLabel"))
        self.label82.setText(_translate("Login_page", "TextLabel"))
        self.label83.setText(_translate("Login_page", "TextLabel"))
        self.label84.setText(_translate("Login_page", "TextLabel"))
        self.label85.setText(_translate("Login_page", "TextLabel"))
        self.label86.setText(_translate("Login_page", "TextLabel"))
        self.label54.setText(_translate("Login_page", "TextLabel"))
        self.label72.setText(_translate("Login_page", "TextLabel"))
        self.label57.setText(_translate("Login_page", "TextLabel"))
        self.label64.setText(_translate("Login_page", "TextLabel"))
        self.label53.setText(_translate("Login_page", "TextLabel"))
        self.label56.setText(_translate("Login_page", "TextLabel"))
        self.label58.setText(_translate("Login_page", "TextLabel"))
        self.label73.setText(_translate("Login_page", "TextLabel"))
        self.label61.setText(_translate("Login_page", "TextLabel"))
        self.label63.setText(_translate("Login_page", "TextLabel"))
        self.label62.setText(_translate("Login_page", "TextLabel"))
        self.label14.setText(_translate("Login_page", "TextLabel"))
        self.label11.setText(_translate("Login_page", "TextLabel"))
        self.label13.setText(_translate("Login_page", "TextLabel"))
        self.label15.setText(_translate("Login_page", "TextLabel"))
        self.label66.setText(_translate("Login_page", "TextLabel"))
        self.label65.setText(_translate("Login_page", "TextLabel"))
        self.label17.setText(_translate("Login_page", "TextLabel"))
        self.label74.setText(_translate("Login_page", "TextLabel"))
        self.label18.setText(_translate("Login_page", "TextLabel"))
        self.label76.setText(_translate("Login_page", "TextLabel"))
        self.label21.setText(_translate("Login_page", "TextLabel"))
        self.label12.setText(_translate("Login_page", "TextLabel"))
        self.label67.setText(_translate("Login_page", "TextLabel"))
        self.label41.setText(_translate("Login_page", "TextLabel"))
        self.label68.setText(_translate("Login_page", "TextLabel"))
        self.label71.setText(_translate("Login_page", "TextLabel"))
        self.label75.setText(_translate("Login_page", "TextLabel"))
        self.label55.setText(_translate("Login_page", "TextLabel"))
        self.New_btn.setText(_translate("Login_page", "Set a new catalogue"))
        self.comboBox.setCurrentText(_translate("Login_page", "Or select an exist catalogue"))
        self.comboBox.setItemText(0, _translate("Login_page", "Or select an exist catalogue"))
        self.pushButton.setText(_translate("Login_page", "Import picture"))
        self.pushButton_2.setText(_translate("Login_page", "Save"))


